Repository mandiant/flare-vm, pull requests merged in 2023-11, with the labels that each got.

#527 Add .NET Framework 3.5 to default config
  config.xml
Labels: :gem: enhancement

#536 Fix: Removing comment from CustomStartLayout.xml
  CustomStartLayout.xml
Labels: :bug: bug

#539 config.xml: Hide the .lnk extension
  config.xml
Labels: :gem: enhancement

#534 config.xml: Add new packages to default config
  config.xml
Labels: :gem: enhancement, :grey_question: discussion

#544 config.xml: Auto arrange Desktop icons
  config.xml
Labels: :gem: enhancement

#543 installer.ps1: Fix CustomStartLayout.xml download
  install.ps1
Labels: :bug: bug

#545 config.xml: Fix hidding .lnk
  config.xml
Labels: :bug: bug
